### ISSUE TITLE
Include ability to keep track of deprecated modules "locally"

### ISSUE THREAD

**Issue by sneat** [League-of-Foundry-Developers/FoundryVTT-Deprecated-Modules#1]
Have you thought about having a list of deprecated modules listing embedded inside this module? Relying on the author of the module to update their manifest may not occur. For instance, those modules that the League takes over due to abandonment, those are unlikely to get an update to the original module's manifest, but this module could be used as a means to redirect those users to the maintained version?

**Comment by BradfordC** [comment]
The main way this checks for deprecated modules is actually just a hard-coded list of deprecated modules; the Manifest+ integration is just an extra bonus.

As for the abandoned & relocated modules, they were originally planned to be detected, but I've heard that one of the Foundry 0.8.x updates is supposed to address the issue, so I've been holding off on it.

**Comment by sneat** [comment]
Ahh apologies, I had a look at the source to see if there was a hardcoded list, but couldn't see one. Turns out I didn't look in the warnings.js file. Good job!
