### ISSUE TITLE
Suggesting a "good" replacement of the same "bad" module - mistaken ID of deprecated module

### ISSUE THREAD

**Issue by buttonpushertv** [League-of-Foundry-Developers/FoundryVTT-Deprecated-Modules#2]
First time loading this module into my existing 5e world. It informs me that the D&D Beyond Importer module I have installed is deprecated and suggests I install Mr. Primate's D&D Beyond Importer module instead...except, that's what I have installed. VTTA's is on the server but not active. VTTA was the first importer used (and then disabled), so could there be some left over bits hanging around in the data & that's what this module is seeing?

![screenshot 1617807032](https://user-images.githubusercontent.com/24526709/113887759-c4096680-978f-11eb-9f99-5947ccfd4aa4.png)

**Comment by BradfordC** [comment]
Thanks for the report. There's a *really* old importer that's being checked for that I didn't realize shared the same ID as Mr. Primate's importer, which is what caused the issue. This will be fixed in the next update.
