### ISSUE TITLE
Language JSON path lang/en.json does not exist

### ISSUE THREAD

**Issue by jocolamarco** [League-of-Foundry-Developers/FoundryVTT-Deprecated-Modules#5]
FVTT 0.8.7
Module version: 1.1.3 (latest)

Error message is logged:
FoundryVTT | 2021-06-22 14:56:41 | [error] Invalid language definition in Package deprecated-modules: Language JSON path lang/en.json does not exist

**Comment by BradfordC** [comment]
Fixed in 1.1.4
